#! /bin/sh
#
# Starts markerless-detector
#
TEMPLATES_B=/etc/MarkerlessDetector/atomeMiniBlue.png
TEMPLATES_G=/etc/MarkerlessDetector/atomeMiniGreen.png
TEMPLATES_R=/etc/MarkerlessDetector/atomeMiniRed.png
SIZE=4.23

start() {
	python /etc/MarkerlessDetector/identifier.py -t $TEMPLATES_B $TEMPLATES_G $TEMPLATES_R -s $SIZE
}

stop() {
	# Somewhat hackish, but this was only way I could think of :)
	line=`ps | grep python`
	pid=`echo $line | cut -d ' ' -f 1`
	kill $pid
	sleep 1
	echo "OK"
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
